const { contextBridge, ipcRenderer } = require('electron');

const invoke = (channel, ...args) => ipcRenderer.invoke(channel, ...args);

contextBridge.exposeInMainWorld('forkline', {
  debugGraphLayout: process.env.DEBUG_GRAPH_LAYOUT === '1',
  chooseRepository: () => invoke('repository:choose'),
  initializeRepository: (initialBranch = 'main') => invoke('repository:initialize', initialBranch),
  cloneRepository: (source, directoryName) => invoke('repository:clone', source, directoryName),
  restoreRepository: () => invoke('repository:restore'),
  repositoryTabs: () => invoke('repository:tabs'),
  activateRepository: (repository) => invoke('repository:activate', repository),
  closeRepository: (repository) => invoke('repository:close', repository),
  refresh: () => invoke('repository:refresh'),
  runAiCommand: (instruction) => invoke('repository:run-ai-command', instruction),
  undo: (count = 1) => invoke('repository:undo', count),
  redo: (count = 1) => invoke('repository:redo', count),
  openTerminal: () => invoke('shell:open-terminal'),
  openFile: (file) => invoke('shell:open-file', file),
  openRepositoryFolder: () => invoke('shell:open-repository-folder'),
  setExternalEditor: (command) => invoke('application:set-external-editor', command),
  aiConfiguration: () => invoke('application:ai-configuration'),
  setAiSettings: (settings) => invoke('application:set-ai-settings', settings),
  clearAiAnalyses: () => invoke('application:clear-ai-analyses'),
  gitProfiles: () => invoke('repository:git-profiles'),
  saveGitProfile: (profile) => invoke('repository:save-git-profile', profile),
  applyGitProfile: (profileId, remember = true) => invoke('repository:apply-git-profile', profileId, remember),
  deleteGitProfile: (profileId) => invoke('repository:delete-git-profile', profileId),
  setIdentity: (name, email, scope = 'local') => invoke('repository:set-identity', name, email, scope),
  setCommitPreferences: (options) => invoke('repository:set-commit-preferences', options),
  addSubmodule: (url, submodulePath, branch = '') => invoke('repository:add-submodule', url, submodulePath, branch),
  updateSubmodule: (submodulePath) => invoke('repository:update-submodule', submodulePath),
  syncSubmodule: (submodulePath) => invoke('repository:sync-submodule', submodulePath),
  deinitializeSubmodule: (submodulePath, force = false) => invoke('repository:deinitialize-submodule', submodulePath, force),
  openSubmodule: (submodulePath) => invoke('repository:open-submodule', submodulePath),
  addWorktree: (options) => invoke('repository:add-worktree', options),
  removeWorktree: (worktreePath, force = false) => invoke('repository:remove-worktree', worktreePath, force),
  pruneWorktrees: () => invoke('repository:prune-worktrees'),
  openWorktree: (worktreePath) => invoke('repository:open-worktree', worktreePath),
  initializeGitFlow: (options) => invoke('repository:initialize-git-flow', options),
  startGitFlow: (type, name, startPoint = '') => invoke('repository:start-git-flow', type, name, startPoint),
  finishGitFlow: (type, branch) => invoke('repository:finish-git-flow', type, branch),
  trackLfs: (pattern) => invoke('repository:track-lfs', pattern),
  untrackLfs: (pattern) => invoke('repository:untrack-lfs', pattern),
  pullLfs: () => invoke('repository:pull-lfs'),
  pushLfs: () => invoke('repository:push-lfs'),
  diff: (file, staged) => invoke('repository:diff', file, staged),
  stashDiff: (ref) => invoke('repository:stash-diff', ref),
  stashAnalysis: (ref, hash) => invoke('repository:stash-analysis', ref, hash),
  analyzeStash: (ref, hash) => invoke('repository:analyze-stash', ref, hash),
  deleteStashAnalysis: (ref, hash) => invoke('repository:delete-stash-analysis', ref, hash),
  wipAnalysis: () => invoke('repository:wip-analysis'),
  analyzeWip: () => invoke('repository:analyze-wip'),
  deleteWipAnalysis: () => invoke('repository:delete-wip-analysis'),
  stage: (files) => invoke('repository:stage', files),
  unstage: (files) => invoke('repository:unstage', files),
  applyHunk: (patch, staged, reverse) => invoke('repository:apply-hunk', patch, staged, reverse),
  resolveConflict: (file, strategy) => invoke('repository:resolve-conflict', file, strategy),
  resolveAllConflicts: () => invoke('repository:resolve-all-conflicts'),
  conflictVersions: (file) => invoke('repository:conflict-versions', file),
  resolveConflictContent: (file, content) => invoke('repository:resolve-conflict-content', file, content),
  commit: (message, options = {}) => invoke('repository:commit', message, options),
  createStash: (options) => invoke('repository:create-stash', options),
  applyStash: (ref, files = []) => invoke('repository:apply-stash', ref, files),
  popStash: (ref) => invoke('repository:pop-stash', ref),
  renameStash: (ref, message) => invoke('repository:rename-stash', ref, message),
  dropStash: (ref) => invoke('repository:drop-stash', ref),
  exportStashPatch: (ref, suggestedName) => invoke('repository:export-stash-patch', ref, suggestedName),
  switchBranch: (name) => invoke('repository:switch', name),
  createBranch: (name, startPoint = null, checkout = true) => invoke('repository:create-branch', name, startPoint, checkout),
  checkoutCommit: (hash) => invoke('repository:checkout-commit', hash),
  mergeBranch: (name) => invoke('repository:merge-branch', name),
  rebaseBranch: (name) => invoke('repository:rebase-branch', name),
  fastForwardBranch: (name) => invoke('repository:fast-forward-branch', name),
  cherryPick: (hash) => invoke('repository:cherry-pick', hash),
  revertCommit: (hash) => invoke('repository:revert-commit', hash),
  resetCommit: (hash, mode) => invoke('repository:reset-commit', hash, mode),
  renameBranch: (oldName, newName) => invoke('repository:rename-branch', oldName, newName),
  deleteBranch: (name, force = false) => invoke('repository:delete-branch', name, force),
  deleteBranchWithRemote: (name, upstream) => invoke('repository:delete-branch-with-remote', name, upstream),
  setUpstream: (branch, remote, remoteBranch) => invoke('repository:set-upstream', branch, remote, remoteBranch),
  checkoutRemoteBranch: (remoteBranch, localName = null) => invoke('repository:checkout-remote-branch', remoteBranch, localName),
  pushBranch: (branch, options = {}) => invoke('repository:push-branch', branch, options),
  addRemote: (name, url) => invoke('repository:add-remote', name, url),
  renameRemote: (oldName, newName) => invoke('repository:rename-remote', oldName, newName),
  removeRemote: (name) => invoke('repository:remove-remote', name),
  fetchRemote: (name, prune = false) => invoke('repository:fetch-remote', name, prune),
  compareWorktree: (revision) => invoke('repository:compare-worktree', revision),
  compareRevisions: (fromRevision, toRevision) => invoke('repository:compare-revisions', fromRevision, toRevision),
  searchHistory: (criteria, limit = 100) => invoke('repository:search-history', criteria, limit),
  fileHistory: (file, limit = 100) => invoke('repository:file-history', file, limit),
  blame: (file, revision = 'HEAD') => invoke('repository:blame', file, revision),
  commitFiles: (revision) => invoke('repository:commit-files', revision),
  commitFileDiff: (revision, file) => invoke('repository:commit-file-diff', revision, file),
  commitAnalysis: (revision) => invoke('repository:commit-analysis', revision),
  analyzeCommit: (revision) => invoke('repository:analyze-commit', revision),
  deleteCommitAnalysis: (revision) => invoke('repository:delete-commit-analysis', revision),
  exportCommitPatch: (revision, suggestedName) => invoke('repository:export-commit-patch', revision, suggestedName),
  applyPatch: () => invoke('repository:apply-patch'),
  applyPatchContent: (patch) => invoke('repository:apply-patch-content', patch),
  createTag: (name, revision, message = '') => invoke('repository:create-tag', name, revision, message),
  deleteTag: (name) => invoke('repository:delete-tag', name),
  pushTag: (name, remote = null) => invoke('repository:push-tag', name, remote),
  deleteRemoteTag: (name, remote = null) => invoke('repository:delete-remote-tag', name, remote),
  amendHeadMessage: (message) => invoke('repository:amend-head-message', message),
  interactiveRebasePlan: (baseRevision) => invoke('repository:interactive-rebase-plan', baseRevision),
  interactiveRebase: (baseRevision, plan) => invoke('repository:interactive-rebase', baseRevision, plan),
  continueOperation: (type, options = {}) => invoke('repository:continue-operation', type, options),
  abortOperation: (type) => invoke('repository:abort-operation', type),
  fetch: () => invoke('repository:fetch'),
  pull: (options = {}) => invoke('repository:pull', options),
  push: (options = {}) => invoke('repository:push', options),
  onRepositoryUpdated: (callback) => ipcRenderer.on('repository:updated', (_event, snapshot) => callback(snapshot)),
});
